### ISSUE TITLE
Gh-pages and master are not even with each other

### ISSUE THREAD

**Issue by sukiletxe** [westonruter/ipa-chart#9]

**Comment by westonruter** [comment]
This is intentional. I have some extra stuff in `gh-pages` which is only applicable there: https://github.com/westonruter/ipa-chart/compare/master...gh-pages

**Comment by sukiletxe** [comment]
But try comparing gh-pages...master 
<https://github.com/westonruter/ipa-chart/compare/gh-pages...master>. 
You have two unmerged commits there.

**Comment by westonruter** [comment]
You're right 👍
